# The repository "Sponsor" button. GrowlerDB is bootstrapped and independent. We deliberately do NOT
# point the Sponsor button at the commercial-license sales page — that isn't sponsorship. Individual
# sponsorship can be enabled here once GitHub Sponsors is set up for the maintainer; commercial/OEM
# licensing + support is described in SUPPORT.md / COMM-LICENSE.md instead.
# github: [qikijames]   # uncomment once GitHub Sponsors is set up
